Fixed #397: add cpp support
libgd/libgd pull request #554
Opened 2019-11-16 10:20 UTC by willson-chen

original patch by Galik. Related PR #398

2019-11-27 06:08 UTC, vapier commented
afaict, this is the same as the previous PR, which means none of the concerns have been addressed.  please see the discussion in #397.

2019-11-28 02:41 UTC, willson-chen commented
@vapier hi, two questions:
* should we support cpp in GD-2.3? by inistalling `gd_io_stream.h` and related files.
* we add `gdpp.cxx` and `gd_io_stream.cxx` to `src/CMakeLists.txt`, but exclude them in `src/Makefile.am`. what is the reason?

2019-11-28 21:37 UTC, vapier commented
we should have a --enable-cxx option to configure.ac so people can control it

would also be nice if we could link the code into libgd w/out requiring libstdc++, but i'm not sure how easy that'll be to pull off

2019-11-29 09:36 UTC, willson-chen commented
> we should have a --enable-cxx option to configure.ac so people can control it

easy to implement. but could you please tell me the reason? although most libgd users do not need c++ wrapper, integrating libgd with c++ sounds resonable considering gcc and g++ are always installed together in Linux.

and reference to my question 2, we should include `gdpp.cxx` and `gd_io_stream.cxx` only when option `--enable-cxx` or `-DENABLE_CXX` is supplied, right?

> would also be nice if we could link the code into libgd w/out requiring libstdc++, but i'm not sure how easy that'll be to pull off

we use iostream in `gd_io_stream.h`, and it depends on libstdc++. AFAIK, libgd with c++ wrapper independent of libstdc++ seems impossible.

2019-12-02 08:45 UTC, willson-chen commented
@vapier , hi, i added `--enable-cxx` option in my last commit. is it what we want? please have a review.

thx

2019-12-10 08:17 UTC, vapier commented
> integrating libgd with c++ without any option sounds resonable considering the relation between c and c++.

sorry but I don't know what you mean by relation.

libgd today does not require a C++ compiler or C++ runtime. that's good for embedded situations that don't have C++ compilers, and even on regular systems where we don't waste resources loading large and normally unused C++ runtimes.

a common idiom in other projects seems to provide in an entirely sep lib like libgdxx.so or libgdcpp.so. that would hold all the C++ bits and not penalize everyone else.

2019-12-11 16:00 UTC, willson-chen commented
> > integrating libgd with c++ without any option sounds resonable considering the relation between c and c++.
> 
> sorry but I don't know what you mean by relation.
> 
> libgd today does not require a C++ compiler or C++ runtime. that's good for embedded situations that don't have C++ compilers, and even on regular systems where we don't waste resources loading large and normally unused C++ runtimes.
> 
> a common idiom in other projects seems to provide in an entirely sep lib like libgdxx.so or libgdcpp.so. that would hold all the C++ bits and not penalize everyone else.

So a better way to support C++ is to generate `libgdcpp.so` when option `--enable-cxx` is on?

2021-03-03 07:01 UTC, vapier requested changes
> So a better way to support C++ is to generate `libgdcpp.so` when option `--enable-cxx` is on?

correct!

> If so, is `libgdcpp.so` the superset of `libgd.so`, or `libgdcpp.so` depends on `libgd.so`?

it would depend on `libgd.so`

2021-03-03 07:01 UTC, vapier commented on configure.ac
> +   Support for cpp wrapper:          $gd_enable_cxx
"CPP wrapper" -> "C++ library"

2021-08-24 11:46 UTC, pierrejoye commented
I see this PR now. Please note I added the ENABLE_CPP option in CMake, so it makes perfect sense to have it in configure as well.

I do agree as well on having a libgdcpp library, depending on libgd.so

2021-09-03 04:53 UTC, pierrejoye commented
Are the changes done?

2026-05-25 09:05 UTC, closed without merging

2026-05-25 09:05 UTC, pierrejoye commented
Won't add c++ wrapper or similar, it is relatively easy to do it if one needs it.