Close #334: gdColorMatch(): doubtful algorithm
libgd/libgd pull request #751
Opened 2021-09-05 14:57 UTC by cmb69

We change the algorithm of `gdColorMatch()` to calculate the Euclidean
distance of the color component values, what may require to change some
thresholds in existing code to match the new algorithm, as can be seen
by the need to adapt gdimagecolorreplace.c.

2021-09-06 02:54 UTC, pierrejoye commented
Looks good to me, Thanks @cmb69 !

2021-09-07 03:41 UTC, pierrejoye commented
I think we need a 2.3.3 release, then most likely a 2.3.4. Once 2.3.3 is out (I will try today or later this week), we can branch GD_2_2 and do only sec fixes there. Master will be 2.4 then and merging this PR as well.

Thoughts?

2021-12-14 17:50 UTC, cmb69 commented
It seems that GD-2.3 has already been branched. Any objections to merge this into master?

2023-11-28 07:58 UTC, vapier requested changes
needs a rebase

2023-11-28 07:58 UTC, vapier commented on src/gd_color.c
>   * The threshold method works relatively well but it can be improved.
please update the comment docs to match what the code is doing

2025-01-02 17:11 UTC, cmb69 commented on src/gd_color.c
>   * The threshold method works relatively well but it can be improved.
Done. Note though that the mentioned L\*A\*B and Delta-E variants are orthogonal to my changes. These are about calculating the difference in different color space than (s)RGB (what might indeed be good idea).

My change is only about improving the somewhat arbitrary threshold calculation; `195075` is `3 * 255**2` what would make some sense only if there are no alpha channel differences. Adjusting the old value to `211204` would basically work (identical results for threshold 0 and 100), but has a different distribution (due to sqrt()). For instance:

col1|col2|old|adjusted|new
----|----|--:|------:|--:
0x00000000|0x00000000|0.0|0.0|0.0
0x00000000|0x20404040|6.8|6.3|25.1
0x00000000|0x40808080|27.3|25.2|50.2
0x00000000|0x60c0c0c0|61.4|56.7|75.4
0x00000000|0x7fffffff|108.3|100.0|100.0

The `new` column shows what one would expect (0x40808080 is about half-way off, etc.) The last row shows how bad the old (non-adjusted) calculation was, since it yields a threshold > 100 (although that's not supposed to happen).

2025-01-02 22:26 UTC, cmb69 commented on src/gd_color.c
> +    const float da = (gdImageAlpha(im, col1) - gdImageAlpha(im, col2)) / (float) gdAlphaMax;
I've just learned that [float division might be particularly slow](http://ithare.com/infographics-operation-costs-in-cpu-clock-cycles/). Should check whether this is an issue (`gdColorMatch()` is called in a tight loop).

2026-05-20 12:17 UTC, pierrejoye commented
Finally (!!!) some time to look at some PRs and issues here.

The main issue with the current (private) gdColorMatch used for crop Ops is primarily caused by:

1. I treat alpha like rgb, with a max of 255, that's not the case, it is 127
2. I compared the squared distance against the linear threshold, very hard to control, or creepy

thoughts on:

```c
#define GD_MAX_COLOR_DIST_SQ 260100
int gdColorMatch(gdImagePtr im, int col1, int col2, float threshold)
{
    const int dr = gdImageRed(im, col1)   - gdImageRed(im, col2);
    const int dg = gdImageGreen(im, col1) - gdImageGreen(im, col2);
    const int db = gdImageBlue(im, col1)  - gdImageBlue(im, col2);
    const int da = (gdImageAlpha(im, col1) - gdImageAlpha(im, col2)) * 2;
    const int dist = dr*dr + dg*dg + db*db + da*da;

    const float t = threshold / 100.0f;
    return dist <= (int)(t * t * GD_MAX_COLOR_DIST_SQ);
}
```

added a constant too to make it more clear.

2026-05-25 07:55 UTC, pierrejoye commented
fixed in master, thanks :)

2026-05-25 07:55 UTC, closed without merging