Skip failure tests on riscv64.
libgd/libgd pull request #877
Opened 2024-02-21 07:49 UTC by JasenChao

These two tests don't fit riscv64 and therefore fail at build time, hopefully skipped.
[This](https://openkoji.iscas.ac.cn/koji/buildinfo?buildID=131383) can prove that the modification is valid.

2024-03-12 10:09 UTC, vapier commented on tests/gdimagecopyresampled/bug00201.c
> +#if defined(__MINGW32__) || defined(__aarch64__) || defined(_M_ARM64) || defined(__riscv)
this covers riscv32 & riscv64, but the commit message only says riscv64

2024-12-28 02:51 UTC, vapier requested changes

2024-12-28 02:51 UTC, vapier commented on tests/gdimagegrayscale/basic.c
> +#if defined(__MINGW32__) || defined(__aarch64__) || defined(_M_ARM64) || defined(__riscv)
same issue here -- needs to update comment

2026-05-28 23:58 UTC, pierrejoye commented
Could you try again using master

I migrate those tests a new perceptual diff, instead of exact match or similar, which is fragile and not very resilient to fp rounding diff.

2026-08-20 12:57 UTC, vapier commented
likely no longer relevant after commit f010284fb75defb4e247d404bf488a20542cc407

2026-08-20 12:57 UTC, closed without merging