Transparent support for writing 1bpp and 4bpp BMPs
libgd/libgd pull request #913
Opened 2024-12-25 15:08 UTC by cmb69

As is, we write palette images as 8bpp BMP images.  Besides that this is wasteful, some readers may not even be able to read 8bpp BMP images. Thus, we write palette images with at most two colors as 1bpp BMPs, unless compression is requested, because BMPs do not support compressed encoding of 1bpp images; we write palette images with at most 16 colors as 4bpp BMPs, and apply `BMP_BI_RLE4` compression if requested.

We piggy-back on the existing implementation for `BMP_BI_RLE8`; that keeps it simple, and although it might not yield the best compression, it ought to be good enough.

References:
<https://en.wikipedia.org/wiki/BMP_file_format>
<https://learn.microsoft.com/en-us/windows/win32/gdi/bitmap-compression>

Closes #911.

---

While implementing this, I've noticed that the RLE compression is not quite as good as it could be. While there is room for improvement, it might get pretty tricky, and it may not be worth spending further time on that, given that RLE encoding only yields somewhat good compression for images with few details, anyway.

2024-12-25 15:14 UTC, cmb69 commented
CI failures are unrelated.

2025-01-08 19:07 UTC, vapier requested changes
minor nits

2025-01-08 19:07 UTC, vapier commented on src/gd_bmp.c
> +	rv = gdDPExtractData(out, size);
whitespace change looks unrelated & incorrect ?

2025-01-08 19:07 UTC, vapier commented on tests/bmp/bmp_low_depth.c
> +#include "gd.h"
please add a file header explaining the test

2025-01-08 19:07 UTC, vapier commented on tests/bmp/bmp_low_depth.c
> +int get_bpp(unsigned char *data)
not a big deal, but please mark local funcs as static

2026-07-05 05:22 UTC, pierrejoye commented
Full BMP support is implemented, but OS/2 bmp.

Closing this PR as it is now supported.

Thanks :)

2026-07-05 05:22 UTC, closed without merging